spring.application.name=hogwarts-demo

spring.datasource.url=jdbc:postgresql://localhost:5432/hogwarts
spring.liquibase.change-log=classpath:liquibase/lesson-three.yml
spring.datasource.username=student
spring.datasource.password=chocolatefrog
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
